// src/components/maplibre/MapLibre.vue
<template>
  <div ref="mapDiv" style='width: 100vh; height: 50vh;'></div>
  <template v-if="loaded">
    <slot />
  </template>
</template>

<script setup lang="ts">
import { onMounted, Ref, ref } from "vue";
import maplibregl from "maplibre-gl";
import "maplibre-gl/dist/maplibre-gl.css";
import { provideMap } from "./map.provide";

const mapDiv: Ref<HTMLElement | null> = ref(null);
const loaded = ref(false);
const { setMap } = provideMap({ loaded });

onMounted(() => {
  if (!mapDiv.value) throw new Error("mapDiv is null");
  const style = import.meta.env.VITE_MAPLIBRE_STYLE_URL;
  if (!style) throw new Error("style is null");

  var map = new maplibregl.Map({
    attributionControl: true,
    container: mapDiv.value,
    style: style || 'https://demotiles.maplibre.org/style.json', // stylesheet location
    center: [-74.5, 40], // starting position [lng, lat]
    zoom: 9 // starting zoom
  });
  setMap(map);
  loaded.value = true;
});
</script>

// src/app/map/maplibre.tsx
import React, {createContext, useCallback, useState} from 'react';
import maplibregl from 'maplibre-gl';

type MapLibreContext = {
  map: maplibregl.Map
};

const MapLibreContext = createContext<MapLibreContext | null>(null);

export function MapLibreProvider({ long, lat, children}: {
  long?: number,
  lat?: number
  children: React.ReactNode
}) {

  const [context, setContext] = useState<MapLibreContext | null>(null);

  const mapRef = useCallback((div: HTMLDivElement | null) => {
    if (!div) return;
    const map = new maplibregl.Map({
      attributionControl: true,
      container: "map",
      style:
        "https://api.maptiler.com/maps/basic-v2/style.json?key=FTNrjsa7Nahw874tmMi7", // stylesheet location
      center: [long || -74.5, lat || 40], // starting position [lng, lat]
      zoom: 12, // starting zoom
    });
    setContext({
      map
    });

  }, []);

  const contents = context ? 
    <MapLibreContext.Provider value={context}>
      {children}
    </MapLibreContext.Provider> : <>{children}</>;

  return <div ref={mapRef}>
    {contents}
  </div>;
}
